CustomUser_SSlpayment_ecommerce_pro/urls.py
from django.contrib import admin
from django.urls import path, include

# To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_shop.urls')),
    path('order/', include('app_order.urls')),
    path('account/', include('app_login.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_order/urls.py
from django.urls import path
from app_order import views
app_name = 'app_order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name='order'),
    path('cart/', views.cartview, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
]

app_shop/urls.py
from django.urls import path
from app_shop import views
app_name = 'app_shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetails.as_view(), name='product_details')
]

app_shop/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"

class Product(models.Model):
    mainimage = models.ImageField(upload_to="Products")
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name ='category')
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    price = models.FloatField()
    oldprice = models.FloatField(default=0.0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created']

app_shop/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from app_shop.models import Product
# Create your views here.


class Home(ListView):
    model = Product
    template_name = 'app_shop/home.html'


class ProductDetails(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'app_shop/product_details.html'

templates/app_shop/home.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-5">
  <h2 class="my-5" >Featured Products</h2>
  <div class="row">
    {% for product in object_list %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product">
        <div class="img-wrap">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"> <a href="{% url 'app_shop:product_details' pk=product.pk %}">{{product.name|truncatechars:40}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new" >&#2547; {{product.price|floatformat:2}}</span>
              <span class="price-old" > <strike>&#2547; {{product.oldprice|floatformat:2}}</strike></span>
            </div>
          </div>
        </figcaption>
      </figure>
    </div>
    {% endfor %}
  </div>
</div>


{% endblock content %}

templates/app_shop/product_details.html
{% extends 'base.html' %}
{% block content %}
  <div class="container my-5">
    <div class="card">
      <div class="row">
        <aside class="col-sm-5 border-right">
          <article class="gallery-wrap">
            <div class="img-big-wrap">
              <div>
                <a href="#"> <img src="/media/{{object.mainimage}}"
                style="width:450px"></a>
              </div>
            </div>
          </article>
        </aside>
        <aside class="col-sm-7">
          <article class="card-body p-5">
            <h3 class="title mp-3">{{object.name}}</h3>
            <p class="price-detail-wrap">
              <span class="price h3 text-warning">
                <span class="currency"> BDT &#2547; </span><span class="num">{{object.price}}</span>
              </span>
            </p>
            <dl class="item-property">
              <dt>Description</dt>
              <dd>
                <p>{{object.detail_text|linebreaks}}</p>
              </dd>
            </dl>
            <a href="{% url 'app_order:order' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase"> <i class="fas fa-shopping-cart"></i> Add to Cart</a>
          </article>
        </aside>
      </div>
    </div>
  </div>
{% endblock %}

templates/app_shop/product_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-5">
  <h2 class="my-5" >Featured Products</h2>
  <div class="row">
    {% for product in object_list %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product">
        <div class="img-wrap">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"> <a href="/">{{product.name|truncatechars:40}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new" >&#2547; {{product.price|floatformat:2}}</span>
              <span class="price-old" > <strike>&#2547; {{product.oldprice|floatformat:2}}</strike></span>
            </div>
          </div>
        </figcaption>
      </figure>
    </div>
    {% endfor %}
  </div>
</div>


{% endblock content %}