CustomUser_SSlpayment_ecommerce_pro/urls.py
from django.contrib import admin
from django.urls import path, include

# To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_shop.urls')),
    path('order/', include('app_order.urls')),
    path('account/', include('app_login.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_order/urls.py
from django.urls import path
from app_order import views
app_name = 'app_order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name='order'),
    path('cart/', views.cartview, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
]

app_shop/urls.py
from django.urls import path
from app_shop import views
app_name = 'app_shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetails.as_view(), name='product_details')
]

app_order/models.py
from django.db import models
from django.conf import settings
from app_shop.models import Product

# Create your models here.

class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="cart")
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity= models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.quantity} X {self.item}'
    
    def get_total(self):
        total= self.quantity * self.item.price
        float_total= format(total, '0.2f')
        return float_total


class Order(models.Model):
    order_items = models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=264, blank=True, null=True)
    orderId = models.CharField(max_length=210, blank=True, null=True)

    def get_totals(self):
        total = 0
        for order_item in self.order_items.all():
            total += float(order_item.get_total())
        return total

app_order/views.py
from django.shortcuts import render, get_object_or_404, redirect
#authentications
from django.contrib.auth.decorators import login_required
# model
from app_order.models import Cart, Order
from app_shop.models import Product
# message
from django.contrib import messages

# Create your views here.

@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_item = Cart.objects.get_or_create(item=item, user=request.user, purchased=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.order_items.filter(item=item).exists():
            order_item[0].quantity +=1
            order_item[0].save()
            messages.info(request, "This item quantity was updated")
            return redirect("app_shop:home")
        else:
            order.order_items.add(order_item[0])
            messages.info(request, "This item was added to your cart")
            return redirect("app_shop:home")
    else:
        order = Order(user=request.user)
        order.save()
        order.order_items.add(order_item[0])
        messages.info(request, "This item was added to your cart")
        return redirect("app_shop:home")

# view cart details

@login_required
def cartview(request):
    carts = Cart.objects.filter(user=request.user, purchased = False)
    orders = Order.objects.filter(user=request.user, ordered = False)
    if carts.exists() and orders.exists():
        order = orders[0]
        return render (request, 'app_order/cart.html', context={'carts': carts, 'order':order})
    else:
        messages.warning(request, "Cart empty!")
        return redirect('app_shop: home')

# remove item
@login_required()
def remove_from_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.order_items.filter(item=item).exists():
            order_item = Cart.objects.filter(
                item=item, user=request.user, purchased=False)[0]
            order.order_items.remove(order_item)
            order_item.delete()
            messages.warning(request, "This item was removed form your cart")
            return redirect("app_order:cart")

        else:
            messages.info(request, "This item was not in your cart")
            return redirect("app_shop:home")
    else:
        messages.info(request, "You don't have an active order!")
        return redirect("app_shop:home")

templates/app_order/cart.html
{% extends 'base.html' %} 
{% comment %} 
{% block content %}
<div class="container">
<div class="card">
    <h3>This is Cart Page!</h3>
    {% for cartpro in carts  %}
    Product-name: {{cartpro.item.name}} <br>
    Product-quantity: {{cartpro.quantity}} <br>
    {% endfor %}
</div>
</div>
{% endblock content %} {% endcomment %}

 

{% block content %}
<div class="container my-5">
  <div class="my-5">
    <h2>Your Cart</h2>
  </div>
  <table class="table table-hover" style="width: 100%">
    <thead>
      <tr>
        <th scope="col" width="10%">Sl</th>
        <th scope="col"  width="45%" >Product Name</th>
        <th scope="col"  width="15%" >Quantity</th>
        <th scope="col"  width="20%"  align="right">Price</th>
        <th scope="col"  width="10%" >Remove</th>
      </tr>
    </thead>
    <tbody>
      {% for cart in carts %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{cart.item.name}}</td>


        {% comment %} {% url 'app_Order:decrease' pk=cart.item.pk %} 
        
        {% url 'app_order:remove' pk=cart.item.pk %}, {% url 'App_Payment:checkout' %}
        {% endcomment %}
        <td>
          <a href="/"> <span class="badge badge-light"> <i class="fas fa-minus"></i></span> </a>
          {{ cart.quantity }}
          <a href="/"> <span class="badge badge-light"> <i class="fas fa-plus"></i></span> </a>
        </td>
        <td>{{cart.get_total}}<span> &#2547;</span></td>
        <td> <a href="{% url 'app_order:remove' pk=cart.item.pk %}" style="color: red;"><i class="far fa-trash-alt"></i></a></td>
      </tr>
      {% endfor %}
      <tr>
        <th scope="row"></th>
        <td colspan="2">Total</td>
        <td align="right">&#2547; {{ order.get_totals | floatformat:2 }}</td>
        <td></td>
      </tr>
      <tr>
        <th scope="row"></th>
        <td colspan="4" class="text-right">
          <a href="{% url 'app_shop:home' %}" class="btn btn-warning mr-4">Continue shopping</a>
          <a href="" class="btn btn-success mr-4">Proceed To Checkout</a>
        </td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}