CustomUser_SSlpayment_ecommerce_pro/urls.py
from django.contrib import admin
from django.urls import path, include

# To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_shop.urls')),
    path('order/', include('app_order.urls')),
    path('account/', include('app_login.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_login/urls.py
from django.urls import path
from .views import *
app_name = 'app_login'

urlpatterns = [
    path('signup/', sign_up, name='signup'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/', user_profile, name='profile'),
]

app_order/urls.py
from django.urls import path
from app_order import views
app_name = 'app_order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name='order'),
    path('cart/', views.cartview, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
]

app_shop/urls.py
from django.urls import path
from app_shop import views
app_name = 'app_shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetails.as_view(), name='product_details')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Ecommerce by Jakaria{% endblock title %}</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
<style>
    .card {
      height: 350px;
    }

    .card-product:after {
      content:"";
      display: table;
      clear: both;
      visibility: hidden;

    }
    .card-product .price_new, .card-product .price {
      margin-right: 5px;
    }

    .card-product .price-old {
      color: #999;
    }

    .card-product .img-wrap {
      border-radius: 3px 3px 0 0;
      overflow: hidden;
      position: relative;
      height: 220px;
      text-align: center;
    }
    .card-product .img-wrap img {
      max-height: 100%;
      max-width: 100%;
      object-fit: cover;
    }


    .card-product .info-wrap {
      overflow: hidden;
      padding:15px;
      border-top: 1px solid #eee;
    }
    .card-product .action-wrap {
      padding-top: 4px;
      margin-top: 4px;
    }
    .card-product .bottom-wrap {
      padding: 15px;
      border-top: 1px solid #eee;

    }
    .card-Product .title {
      margin-top: 0px;
    }


    </style>
</head>
<body>
 {% include 'navbar.html' %}

    <div class="container" style="padding-top:15px;">

        <div class="messages container mt-2">
            {% if messages %}
            {% for messages in messages %}
            <div {% if messages.tags %} class="alert alert-{{messages.tags}}{% endif %}"
            role="alert">
            {{messages}}
            <button type="button" class="close" data-dismiss="alert" aria-label ="Close"> <span aria-hidden="true" >&times;</span> </button>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        {% block content %}{% endblock content %}

    </div>




<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>
</html>

templates/navbar.html
{% load cart_tag %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'app_shop:home' %}"> <b>ExtraShop</b> </a>

    <button type="button" class="navbar-toggler" data-toggle="collapse"
    data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
    aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
       {% if request.user.is_authenticated %}
      <li class="nav-item">
        {% comment %} <a href="{% url 'app_Order:cart' %}" class="nav-link"> {% endcomment %}
        {% comment %} <a href="{% url 'app_Order:cart' %}" class="nav-link"> {% endcomment %}
        {% comment %} <a href="{% url 'app_Order:cart' %}" class="nav-link"> {% endcomment %}
          <a href="{% url 'app_order:cart' %}" class="nav-link">
          <i class="fa fa-shopping-cart"></i>Cart <span class="badge badge-light">{{ request.user | cart_total }}</span>
          {% comment %} <span class="badge badge-light">{{ request.user }}</span> {% endcomment %}
          
        </a>
      </li>

      <li class="nav-item dropdown mr-3">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-user-tie"></i>
      {{request.user.profile.username}}</a>
      <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
        <a class="dropdown-item" href="{% url 'app_login:profile' %}">Profile</a>
        {% comment %} <a class="dropdown-item" href="{% url 'app_login:profile' %}">Profile</a> {% endcomment %}
        {% comment %} <a class="dropdown-item" href="{% url 'App_Payment:orders' %}">Orders</a> {% endcomment %}
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'app_login:logout' %}">Logout</a>
      </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a href="{% url 'app_login:login' %}" class="btn btn-primary">Login</a>
      </li>
      {% endif %}
    </ul>
   </div>
  </div>
</nav>